### ISSUE TITLE
Erlang 1.1 not compatible with SonarQube 5.3

### ISSUE THREAD

**Issue by henryju** [SonarQubeCommunity/sonar-erlang#14]
ErlangSourceImporter uses ProjectFileSystem that will be removed in SonarQube 5.3. Seems it was already removed so you just have to release a new version.

**Comment by ttoleung** [comment]
It seems you are not getting any replies here, wonder who has the authority to make a new build? It seems the travis build link is also incorrect.

**Comment by dbolkensteyn** [comment]
Feel free to submit a pull request @ttoleung

**Comment by kalidasya** [comment]
I will call a vote
