### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by DilumK** [SonarQubeCommunity/sonar-erlang#18]
Getting parser error for the following code. Using erlang 1.2 Snapshot version. 

20:19:26.849 INFO  - Sensor ErlangSquidSensor
20:19:27.063 ERROR - Unable to parse file: /home/jenkins/PRBT_management_trunk/label/frank/src/prbt_db_connection_handler.erl
20:19:27.066 ERROR - Parse error at line 109 column 14:

 99:    | {stop, Reason :: term(), NewState},
100:  NewState :: term(),
101:  Timeout :: non_neg_integer() | infinity.
102: %% ====================================================================
103: 
104: handle_cast(add_mysql_connection,State) ->
105:  Ref = create_mysql_connection(State#state.reg_name),
106:  {noreply,State#state{db_conn_pid = Ref}};
107:  
108: 
109: handle_cast({query,Query},State) ->
                  ^
110:  Ref = State#state.db_conn_pid,
111:  if
112:   Ref == none ->
113:    NewState = State,
114:    {error, error};
115:   true ->
116:    {NewState, _Reply} = sql_query(Ref, Query, State)
117:  end,
118:  {noreply,NewState};

**Comment by kalidasya** [comment]
@DilumK I will take a look

**Comment by kalidasya** [comment]
@DilumK the issue is that the query is not a keyword anymore, patch is on its way
