### ISSUE TITLE
Incompatibility with SQ 6.4 because of code colorizer API

### ISSUE THREAD

**Issue by dbmeneses** [SonarQubeCommunity/sonar-erlang#21]
The code colorizer API (deprecated since 4.5.2) will be removed in SonarQube 6.4. More details here:
https://jira.sonarsource.com/browse/SONAR-7860

Erlang plugin is currently still using it, which would make it incompatible with SonarQube 6.4. It should use directly the highlighting mechanism available in the SensorContext.

**Comment by kalidasya** [comment]
@dbmeneses on Sundays I work on getting erlang plugin up to date with the 5.6 API, but it does not go fast as there are a lot of changes (see https://github.com/SonarQubeCommunity/sonar-erlang/tree/sonarqube56 branch)

**Comment by kalidasya** [comment]
sonar api version was updated to 6.7
