### ISSUE TITLE
New maintained fork

### ISSUE THREAD

**Issue by DaniruKun** [SonarQubeCommunity/sonar-erlang#41]
@kalidasya as agreed, here is link to our new maintained fork of the plugin: https://github.com/evolution-gaming/sonar-erlang

It is possible to build a working version of the plugin, and we will keep maintaining it to make sure it is compatible with latest Sonar server versions.

**Comment by kalidasya** [comment]
updated the readme, people should find your version. we might want to take this down or you take this repo over in the future. but for now this should be fine
